server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # SPA fallback: si no encuentra el archivo, sirve index.html
        try_files $uri $uri/ /index.html;
    }

    # Cachear archivos estáticos para optimizar tiempos de carga
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}